### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by geert2** [DeuxVis/Lora-TTNMapper-T-Beam#18]
While compiling I get errors. 

Firstly, it does not find #include "gps.h"

and it stops there : 

"Multiple libraries were found for "TinyGPS++.h"
Lora-TTNMapper-T-Beam:12:17: error: gps.h: No such file or directory
 Used: /Users/geertvansintjan/Documents/Arduino/libraries/TinyGPSPlus-1.0.2b
compilation terminated.
Multiple libraries were found for "lmic.h"
 Used: /Users/geertvansintjan/Documents/Arduino/libraries/IBM_LMIC_framework
 Not used: /Users/geertvansintjan/Documents/Arduino/libraries/MCCI_LoRaWAN_LMIC_library
exit status 1
gps.h: No such file or directory

When doing a file search however, I find a gps.h in the LoRa_Node library, somewhere...

PS. a few lines further the line gps gps;  seems strange too?

**Comment by DeuxVis** [comment]
You maybe have some problems with your arduino IDE installation. I recently had to reinstall everything from scratch too, with different but similar errors.

For reference I use those versions which works for me : 

- arduino IDE 1.8.10
- esp32 boards by Espressif Systems version 1.0.4 (from the boards manager) and I choose board type "T-Beam".
- IBM LMIC Framework by IBM version 1.5.0+arduino-2 (from the library manager)
- TinyGPSPlus version 1.0.2b (manually installed)

Extract from my build log :
```
Multiple libraries were found for "lmic.h"
 Used: /home/myuser/Arduino/libraries/IBM_LMIC_framework
Multiple libraries were found for "TinyGPS++.h"
 Used: /home/myuser/Arduino/libraries/TinyGPSPlus
[...]
Using library IBM_LMIC_framework at version 1.5.0 arduino-2 in folder: /home/myuser/Arduino/libraries/IBM_LMIC_framework 
Using library TinyGPSPlus at version 1.0.2 in folder: /home/myuser/Arduino/libraries/TinyGPSPlus 
```

Those "multiple library found" warnings are not a problem as long it picks the right one - which seems the case for you too.

"gps gps;" is just declaration of an instance of class "gps" called "gps". I reckon it might look confusing, will think try to remember changing that.

I'm more puzzled by why it cannot find "gps.h" to include from the same folder as the ".ino" file... did you clone or updated from my master branch recently ?

**Comment by DeuxVis** [comment]
Oh by the way the instruction installation for tinygpsplus says you should rename "/Users/geertvansintjan/Documents/Arduino/libraries/TinyGPSPlus-1.0.2b" to "/Users/geertvansintjan/Documents/Arduino/libraries/TinyGPSPlus".

No idea if that is the source of your problem then.

**Comment by geert2** [comment]
So yes. The problem was on my side. User error as they say. (I just ran the main file instead of donwloading, renaming and using the complete folder). 

It compiles smoothly. Now is the time to upload it. 

Before I do this, another question: the keys: I don't find an Appkey on the device page?

I understand I just copy the msb device address including the brackets? like this:  { 0x26, 0x01, 0x10, 0x14 } the number in the code  seems to suggest another format. 

Please bear with me, I am new to Lora, and don't know what  degree of stupid questions experienced programmers here accept from idiots. 

Kind regards!

**Comment by geert2** [comment]
One more issue resolved: I need to have the OTA setting , and the Appkey shows up.  No GPS fix. But it is very cold outside. It will be tomorrow.

**Comment by DeuxVis** [comment]
Glad you solved your problems.

Yeah GPS fix is nearly impossible to get inside. Especially with the T-Beam provided GPS antenna, which isn't very good.
With a better GPS antenna I can go outside under the clear sky to get a fix and then - without shutting down the board - get back inside where it still get enough GPS signal to continue working - but your mileage may vary depending on your building situation.
