### ISSUE TITLE
How to retrieve NwksKey

### ISSUE THREAD

**Issue by DuckY1987** [DeuxVis/Lora-TTNMapper-T-Beam#7]
I'm rather new to ttn, but i don't know how to retrieve the nwks for the config.h

I know its derived from some other unique id's, so do i need to fill it as i understood its a session based key, which i don't know and only the device and the network server will know it.

Is the deviceAddress custom generated or is it the Device EUI?

Thanks a lot :-).

**Comment by DeuxVis** [comment]
As commented in the config.h file it is named "network session key" in the TTN interface.

![nwsk_on_ttn_console](https://user-images.githubusercontent.com/2444564/44839470-29436580-ac3f-11e8-9e6a-37477c25b055.png)

**Comment by DuckY1987** [comment]
Okay there we face a problem, i dont have this session key in my overview :-(.

![image](https://user-images.githubusercontent.com/16365083/44840129-bdfa9300-ac40-11e8-91b6-a613ed743352.png)

**Comment by DeuxVis** [comment]
Yes you have to use ABP authentication fo now.

And yes  DeviceAdress is hexadecimal.
