### ISSUE TITLE
Payload error "json: unsupported value: NaN"

### ISSUE THREAD

**Issue by HaViGit** [DeuxVis/Lora-TTNMapper-T-Beam#9]
Hi,

Not very experienced with LoRa/TTN I'm installing the TTN-Mapper on my TTGO-T-Beam V2. An issue is shown when I enter your payload code 1:1 to the TTN-Console, it reports an error after testing as shown in the attachment. Can you tell me what I'm doing wrong?

Regards, Hans.

![payload](https://user-images.githubusercontent.com/46343309/51328407-9aab7580-1a73-11e9-9016-eff033e271c1.JPG)

**Comment by HaViGit** [comment]
Thanks for your reply. It turned out I made a newbie mistake by leaving the Payload field empty, if it is filled in it works ;-)

**Comment by adrianomourapeixoto** [comment]
hello i'm facing the same problem. how did you solve it?

**Comment by HaViGit** [comment]
Hi.

Because TTN-mapper website works too slow on my system I now use a tracker from Peter Javorsky: https://github.com/tekk/TTGO-T-Beam-Car-Tracker. This works with Cayenne and is based on the perfect work of DeuxVis.

Ragards, Hans.
